wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.19
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.13
    start_time: 1656186497
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 1
      4: 3.8.13
      5: 0.12.19
      8:
      - 3
      - 5
